// F2-07 item A (netyvee/app#344) — shared markdown blog loader, lifted from
// netyvee/vigil-cleaning and netyvee/security's near-identical
// lib/blog/markdownPosts.ts. No real markdown posts are committed to either
// repo yet (content/blog/ exists but is empty — posts are generated by the
// CRM's BlogChannelAdapter at runtime), so these tests use synthetic
// fixtures written to a temp dir rather than a real-content snapshot (the
// pattern tests/fixtures-data/real-prose-sections.json uses elsewhere).
//
// Two concerns:
// 1. The loader computes the exact same fields the two original per-repo
//    loaders did (readTime, tags, category, excerpt, intro/body split,
//    related posts, image fallback to the F2-06 sentinel), parameterised by
//    site identity instead of a hardcoded SITE constant.
// 2. The shared summary/post shape resolves the two sites' genuine field
//    differences (Cleaning: readTime+tags; Security: image) as additive
//    fields computed unconditionally for every consumer.
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createMarkdownBlogLoader, buildMarkdownBlogJsonLd, type MarkdownBlogIdentity } from '../src/blog/markdownLoader';
import { SENTINEL_IMAGE_PATH } from '../src/types';

const CLEANING_IDENTITY: MarkdownBlogIdentity = {
  division: 'cleaning',
  host: 'https://cleaning.vigilservices.co.uk',
  name: 'Vigil Cleaning Services',
  enquiryUrl: 'https://app.vigilservices.co.uk/enquire/cleaning',
  phone: '020 3098 6037',
  ctaLabel: 'Talk to our cleaning team',
};

const SECURITY_IDENTITY: MarkdownBlogIdentity = {
  division: 'security',
  host: 'https://security.vigilservices.co.uk',
  name: 'Vigil Security Services',
  enquiryUrl: 'https://app.vigilservices.co.uk/enquire/security',
  phone: '020 3973 8892',
  ctaLabel: 'Get a security quote',
};

let dir: string;
beforeEach(() => {
  dir = mkdtempSync(path.join(tmpdir(), 'vf-blog-'));
  mkdirSync(path.join(dir, 'content', 'blog'), { recursive: true });
});
afterEach(() => rmSync(dir, { recursive: true, force: true }));

function writePost(slug: string, frontmatter: Record<string, unknown>, body: string) {
  const fm = Object.entries(frontmatter)
    .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
    .join('\n');
  const content = `---\n${fm}\n---\n\n${body}\n`;
  writeFileSync(path.join(dir, 'content', 'blog', `${slug}.md`), content);
}

describe('createMarkdownBlogLoader — site identity scoping', () => {
  it('scopes seo.canonical, author fallback and CTA to the given identity, not a hardcoded one', () => {
    writePost(
      'tupe-guide',
      { title: 'The TUPE Guide', date: '2026-05-01', service_type: 'office-cleaning', borough: 'westminster' },
      '<p>Switching contractors triggers TUPE.</p><p>Here is the full guide body.</p>'
    );
    const loader = createMarkdownBlogLoader(CLEANING_IDENTITY, { blogDir: path.join(dir, 'content', 'blog') });
    const post = loader.getMarkdownPost('tupe-guide')!;

    expect(post.division).toBe('cleaning');
    expect(post.data.seo.canonical).toBe('https://cleaning.vigilservices.co.uk/blog/tupe-guide');
    expect(post.data.seo.title).toBe('The TUPE Guide | Vigil Cleaning Services');
    expect(post.data.author).toBe('Vigil Cleaning Services team');
    expect(post.data.cta).toEqual({
      primaryLabel: 'Talk to our cleaning team',
      primaryUrl: 'https://app.vigilservices.co.uk/enquire/cleaning',
      phone: '020 3098 6037',
      phoneLabel: 'Call 020 3098 6037',
    });
  });

  it('the exact same markdown file loaded under Security identity scopes to Security instead', () => {
    writePost('tupe-guide', { title: 'The TUPE Guide', date: '2026-05-01' }, '<p>Body.</p>');
    const loader = createMarkdownBlogLoader(SECURITY_IDENTITY, { blogDir: path.join(dir, 'content', 'blog') });
    const post = loader.getMarkdownPost('tupe-guide')!;

    expect(post.division).toBe('security');
    expect(post.data.seo.canonical).toBe('https://security.vigilservices.co.uk/blog/tupe-guide');
    expect(post.data.cta.primaryUrl).toBe('https://app.vigilservices.co.uk/enquire/security');
    expect(post.data.cta.phone).toBe('020 3973 8892');
  });
});

describe('createMarkdownBlogLoader — field derivations (ported unchanged from both original loaders)', () => {
  const loader = () => createMarkdownBlogLoader(CLEANING_IDENTITY, { blogDir: path.join(dir, 'content', 'blog') });

  it('splits the first <p> as intro, drops it from body so it does not render twice', () => {
    writePost('post', { title: 'Post', date: '2026-01-01' }, '<p>Intro paragraph.</p><p>Second paragraph.</p>');
    const post = loader().getMarkdownPost('post')!;
    expect(post.data.intro).toBe('<p>Intro paragraph.</p>');
    expect(post.data.body).not.toContain('Intro paragraph.');
    expect(post.data.body).toContain('Second paragraph.');
  });

  it('computes readTime as ceil(wordCount / 200), minimum 1', () => {
    const words = Array.from({ length: 450 }, (_, i) => `word${i}`).join(' ');
    writePost('long-post', { title: 'Long Post', date: '2026-01-01' }, `<p>${words}</p>`);
    const post = loader().getMarkdownPost('long-post')!;
    expect(post.data.readTime).toBe(3); // ceil(450/200) = 3
  });

  it('derives tags from service_type + borough front matter, filtering absent ones', () => {
    writePost('post', { title: 'Post', date: '2026-01-01', service_type: 'office-cleaning', borough: 'camden' }, '<p>Body.</p>');
    const post = loader().getMarkdownPost('post')!;
    expect(post.data.tags).toEqual(['office-cleaning', 'camden']);
  });

  it('falls back image to the shared F2-06 sentinel when front matter has none', () => {
    writePost('post', { title: 'Post', date: '2026-01-01' }, '<p>Body.</p>');
    const post = loader().getMarkdownPost('post')!;
    expect(post.data.images.header.src).toBe(SENTINEL_IMAGE_PATH);
    expect(post.data.images.og.src).toBe(SENTINEL_IMAGE_PATH);
  });

  it('uses a real front-matter image when present', () => {
    writePost('post', { title: 'Post', date: '2026-01-01', image: '/real-image.jpg', image_alt: 'Alt text' }, '<p>Body.</p>');
    const post = loader().getMarkdownPost('post')!;
    expect(post.data.images.header.src).toBe('/real-image.jpg');
    expect(post.data.images.header.alt).toBe('Alt text');
  });

  it('humanises a slug into a title when front matter has no title', () => {
    writePost('office-cleaning-guide', {}, '<p>Body.</p>');
    const post = loader().getMarkdownPost('office-cleaning-guide')!;
    expect(post.data.h1).toBe('Office cleaning guide');
  });

  it('returns null for a slug with no file', () => {
    expect(loader().getMarkdownPost('does-not-exist')).toBeNull();
  });

  it('relatedPosts excludes the current slug, newest first, capped at 3', () => {
    writePost('a', { title: 'A', date: '2026-01-01' }, '<p>A.</p>');
    writePost('b', { title: 'B', date: '2026-02-01' }, '<p>B.</p>');
    writePost('c', { title: 'C', date: '2026-03-01' }, '<p>C.</p>');
    writePost('d', { title: 'D', date: '2026-04-01' }, '<p>D.</p>');
    const post = loader().getMarkdownPost('a')!;
    expect(post.data.relatedPosts.map((r) => r.title)).toEqual(['D', 'C', 'B']);
  });
});

describe('createMarkdownBlogLoader — summary shape resolves both sites genuine field differences', () => {
  it('computes readTime, tags AND image unconditionally, regardless of which site reads which', () => {
    writePost('post', { title: 'Post', date: '2026-01-01', service_type: 'manned-guarding', image: '/guard.jpg' }, '<p>Body text here.</p>');
    const summaries = createMarkdownBlogLoader(SECURITY_IDENTITY, { blogDir: path.join(dir, 'content', 'blog') }).getMarkdownPostSummaries();
    expect(summaries).toHaveLength(1);
    const [s] = summaries;
    // Security's own field:
    expect(s.image).toBe('/guard.jpg');
    // Cleaning's own fields, also present even though Security's rendering never reads them:
    expect(s.readTime).toMatch(/min read$/);
    expect(s.tags).toEqual(['manned-guarding']);
  });

  it('getMarkdownSlugs returns [] and getMarkdownPostSummaries returns [] when content/blog does not exist', () => {
    rmSync(path.join(dir, 'content', 'blog'), { recursive: true, force: true });
    const loader = createMarkdownBlogLoader(CLEANING_IDENTITY, { blogDir: path.join(dir, 'content', 'blog') });
    expect(loader.getMarkdownSlugs()).toEqual([]);
    expect(loader.getMarkdownPostSummaries()).toEqual([]);
  });

  it('summaries sort newest first', () => {
    writePost('old', { title: 'Old', date: '2026-01-01' }, '<p>Old.</p>');
    writePost('new', { title: 'New', date: '2026-06-01' }, '<p>New.</p>');
    const summaries = createMarkdownBlogLoader(CLEANING_IDENTITY, { blogDir: path.join(dir, 'content', 'blog') }).getMarkdownPostSummaries();
    expect(summaries.map((s) => s.slug)).toEqual(['new', 'old']);
  });
});

describe('buildMarkdownBlogJsonLd — BlogPosting node via the shared buildJsonLd()', () => {
  it('emits a BlogPosting node (not Article) with the post fields mapped through', () => {
    writePost('post', { title: 'Post Title', date: '2026-05-01', focus_keyword: 'office cleaning' }, '<p>Intro.</p><p>Body.</p>');
    const loader = createMarkdownBlogLoader(CLEANING_IDENTITY, { blogDir: path.join(dir, 'content', 'blog') });
    const post = loader.getMarkdownPost('post')!;
    const jsonLd = buildMarkdownBlogJsonLd(post.data, CLEANING_IDENTITY, { slug: 'post' });

    const blogPosting = jsonLd['@graph'].find((n: any) => n['@type'] === 'BlogPosting');
    expect(blogPosting).toBeDefined();
    expect(blogPosting.headline).toBe('Post Title | Vigil Cleaning Services');
    expect(blogPosting.datePublished).toBe('2026-05-01');
    expect(jsonLd['@graph'].some((n: any) => n['@type'] === 'Article')).toBe(false);
  });

  it('emits an Organization node scoped to the given identity (never a foreign division NAP)', () => {
    writePost('post', { title: 'Post', date: '2026-05-01' }, '<p>Body.</p>');
    const post = createMarkdownBlogLoader(SECURITY_IDENTITY, { blogDir: path.join(dir, 'content', 'blog') }).getMarkdownPost('post')!;
    const jsonLd = buildMarkdownBlogJsonLd(post.data, SECURITY_IDENTITY, { slug: 'post' });

    const org = jsonLd['@graph'].find((n: any) => n['@type'] === 'Organization');
    expect(org.name).toBe('Vigil Security Services');
    expect(org.telephone).toBe('+442039738892');
    expect(JSON.stringify(jsonLd)).not.toContain('cleaning');
  });

  it('includes a BreadcrumbList Home > Blog > Post', () => {
    writePost('post', { title: 'My Post', date: '2026-05-01' }, '<p>Body.</p>');
    const post = createMarkdownBlogLoader(CLEANING_IDENTITY, { blogDir: path.join(dir, 'content', 'blog') }).getMarkdownPost('post')!;
    const jsonLd = buildMarkdownBlogJsonLd(post.data, CLEANING_IDENTITY, { slug: 'post' });

    const breadcrumbs = jsonLd['@graph'].find((n: any) => n['@type'] === 'BreadcrumbList');
    expect(breadcrumbs.itemListElement.map((i: any) => i.name)).toEqual(['Vigil Cleaning Services', 'Blog', 'My Post']);
  });

  it('includes an FAQPage node only when the post has faqs', () => {
    writePost('post', { title: 'Post', date: '2026-05-01' }, '<p>Body.</p>');
    const loaded = createMarkdownBlogLoader(CLEANING_IDENTITY, { blogDir: path.join(dir, 'content', 'blog') }).getMarkdownPost('post')!;

    const withoutFaqs = buildMarkdownBlogJsonLd(loaded.data, CLEANING_IDENTITY, { slug: 'post' });
    expect(withoutFaqs['@graph'].some((n: any) => n['@type'] === 'FAQPage')).toBe(false);

    const withFaqs = buildMarkdownBlogJsonLd(
      { ...loaded.data, faqs: [{ question: 'Q1?', answer: 'A1.' }] },
      CLEANING_IDENTITY,
      { slug: 'post' }
    );
    const faqNode = withFaqs['@graph'].find((n: any) => n['@type'] === 'FAQPage');
    expect(faqNode.mainEntity[0].name).toBe('Q1?');
    expect(faqNode.mainEntity[0].acceptedAnswer.text).toBe('A1.');
  });
});
